apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis-stack.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: "{{ .Values.name }}"
spec:
  ports:
  - port: {{ .Values.redis_stack_server.port }}
    name: db
  type: NodePort
  selector:
    app: "{{ .Values.name }}"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "redis-stack.fullname" . }}
spec:
  selector:
    matchLabels:
      app: "{{ .Values.name }}" 
  serviceName: "{{ .Values.name }}"
  replicas: {{ .Values.redis_stack_server.replicas }}
  template:
    metadata:
      labels:
        app: "{{ .Values.name }}" 
    spec:
      terminationGracePeriodSeconds: 10
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      containers:
      - name: "{{ .Values.name }}"
        image: {{ .Values.redis_stack_server.image }}:{{ .Values.redis_stack_server.tag }}
        imagePullPolicy: Always
        {{- with .Values.redis_stack_server.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        ports:
        - containerPort: {{ .Values.redis_stack_server.port }}
          name: db
        volumeMounts:
        - name: db
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: db
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ .Values.redis_stack_server.storage_class }}
      resources:
        requests:
          storage: {{ .Values.redis_stack_server.storage }}
