{{- if .Values.featureFlags.enabled }}
apiVersion: core.openfeature.dev/v1beta1
kind: FeatureFlagSource
metadata:
  name: {{ .Chart.Name }}-flags
  labels:
    app.kubernetes.io/name: {{ $.Chart.Name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/component: {{ $.Chart.Name }}
spec:
  sources:
  {{- range .Values.featureFlags.flags }}
    - source: {{ $.Chart.Name }}.{{ .name }}
      provider: kubernetes
  {{- end }}
  port: 8080
{{- range .Values.featureFlags.flags }}
---
apiVersion: core.openfeature.dev/v1beta1
kind: FeatureFlag
metadata:
  name: {{ $.Chart.Name }}.{{ .name }}
  labels:
    app.kubernetes.io/name: {{ $.Chart.Name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/component: {{ $.Chart.Name }}
  annotations:
    featureflags/description: {{ .description | quote }}
    featureflags/owner: {{ .owner }}
spec:
  flagSpec:
    flags:
      {{ .name }}:
        state: {{ .state | quote }}
        defaultVariant: {{ .defaultVariant | quote }}
        variants:
          {{ toJson .variants }}
        {{- if .targeting }}
        targeting:
          {{ toJson .targeting }}
        {{- end }}
{{- end }}
{{- end }}