kind: Secret
apiVersion: v1
metadata:
  name: {{ template "collection-backups.secretName" . }}
  namespace: {{ template "collection-backups.namespace" . }}
  labels:
{{ include "collection-backups.labels" . | indent 4 }}
{{- if .Values.labels }}
{{ toYaml .Values.labels | indent 4 }}
{{- end}}
data:
  cloud: {{ required "A valid .Values.secretCloud entry required!" .Values.secretCloud }}
