{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "collection-backups.serviceAccountName" . }}
  namespace: {{ template "collection-backups.namespace" . }}
  labels:
    {{- include "collection-backups.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
