apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "spark-pod-cleaner.fullname" . }}
  namespace: {{ include "spark-pod-cleaner.namespace" . }}
data:
  clean_pods.sh: |-
    #!/bin/bash
    
    for POD_NAME in $(kubectl get pods --no-headers --field-selector="status.phase!=Running,status.phase!=Pending,status.phase!=ContainerCreating" -l "spark-role in (executor,driver)" --sort-by=.status.startTime 2>/dev/null | grep -v -e ' [0-9]*s$' -e ' [0-4]m[0-9]*s$' | awk '{print $1}') ; do
      kubectl delete pod $POD_NAME 2>/dev/null
    done
    for POD_NAME in $(kubectl get pods --no-headers --field-selector="status.phase!=Running,status.phase!=Pending,status.phase!=ContainerCreating" -l "app.kubernetes.io/name=spark-pod-cleaner" --sort-by=.status.startTime 2>/dev/null | grep -v -e ' [0-9]*s$' -e ' [0-4]m[0-9]*s$' | awk '{print $1}') ; do
      kubectl delete pod $POD_NAME 2>/dev/null
    done

    for POD_NAME in $(kubectl get pods --no-headers --field-selector="status.phase!=Running,status.phase!=Pending,status.phase!=ContainerCreating" -l "app.kubernetes.io/name=collection-backups" --sort-by=.status.startTime 2>/dev/null | grep -e ' [2-9]*d[0-9]*h$' -e ' [0-9][0-9]d$' | awk '{print $1}') ; do
      kubectl delete pod $POD_NAME 2>/dev/null
    done
