apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "spark-pod-cleaner.roleName" . }}
  namespace: {{ include "spark-pod-cleaner.namespace" . }}
  labels:
    {{- include "spark-pod-cleaner.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources:
      - pods
      - pods/log
      - events
    verbs:
      - get
      - list
      - create
      - delete
      - watch
      - update
      - patch
  - apiGroups:
      - extensions
    resources:
      - deployments
      - pods/log
      - pods/status
      - pods/var
    verbs:
      - get
      - list
      - create
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - list
      - create