apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "spark-pod-cleaner.roleBindingName" . }}
  namespace: {{ include "spark-pod-cleaner.namespace" . }}
  labels:
    {{- include "spark-pod-cleaner.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "spark-pod-cleaner.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ include "spark-pod-cleaner.roleName" . }}
  apiGroup: rbac.authorization.k8s.io