apiVersion: v1
appVersion: 1.0.0
description: A Helm chart to deploy fusion collection backups
home: https://github.com/lucidworks-managed-fusion/collection-backups.git
keywords:
  - fusion
  - collections
  - solr
  - lucidworks
  - collection
maintainers:
  - email: irepan.chavez@lucidworks.com
    name: Irepan Chavez
    url: https://github.com/lucidworks-managed-fusion
name: collection-backups
#sources:
#- https://github.com/aws/eks-charts
version: 0.0.2
