schedule: "0 0 0 * * ?"

zookeeperHost:
customerId:
maxBackupPoints: 400
pubSubEnabled: false

bucketName:
gcsMountPath: "/etc/gcs"
excludedCollections: "system_logs"

secretName:
secretCloud:

nodeSelector: {}
securityContext: {}
annotations: {}
labels: {}
imagePullSecrets: []

solrXml:
  version: 1
  xmlFile: ""

image:
  repository: us-west1-docker.pkg.dev/managed-fusion/cloud-support/images
  name: collection-backups
  tag: 1.4.0
  pullPolicy: Always

featureFlags:
  enabled: true  # Enable/disable all feature flags for this service
  flags:
    - name: backup.skip-backups # naming convention: <feature>.<attribute>
      description: "Skips backups regardless of the schedule"
      owner: "derek"
      state: "ENABLED" # or "DISABLED"
      defaultVariant: false
      variants: # for boolean flags
        true: true
        false: false
