schedule: "0 0 0 * * ?"

zookeeperHost:
customerId:
maxBackupPoints: 400
pubSubEnabled: false

bucketName:
gcsMountPath: "/etc/gcs"
excludedCollections: "system_logs"

secretName:
secretCloud:

nodeSelector: {}
securityContext: {}
annotations: {}
labels: {}
imagePullSecrets: []

solrXml:
  version: 1
  xmlFile: ""

image:
  repository: us-docker.pkg.dev/managed-fusion/engineering-tooling-images
  name: collection-backups
  tag: 1.3.0
  pullPolicy: Always
