schedule: "0 0 * * *"

zookeeperHost:
customerId:
maxBackupPoints: 400

bucketName:

secretName:
secretCloud:

nodeSelector: {}
securityContext: {}
annotations: {}
labels: {}
imagePullSecrets: []

solrXml:
  version: 1
  xmlFile: ""

image:
  repository: gcr.io/managed-fusion
  name: collection-backups
  tag: 1.0.0
  pullPolicy: IfNotPresent
