schedule: "0 0 * * *"

zookeeperHost:
customerId:

bucketName:

secretName:
secretCloud:

nodeSelector: {}
securityContext: {}
annotations: {}
labels: {}
imagePullSecrets: []

solrXml:
  version: 1
  xmlFile: ""

image:
  repository: gcr.io/managed-fusion
  name: collection-backups
  tag: 0.9.1
  pullPolicy: IfNotPresent
