---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "solr-autoscaling-operator.serviceAccount" . }}
  namespace: {{ .Release.Namespace }}
  {{- if .Values.annotations }}
  annotations:
    {{ toYaml .Values.annotations 4 }}
  {{- else }}
  {{- with .Values.global }}
  {{- if and .env .project .project.prefix .project.id }}
  annotations:
    iam.gke.io/gcp-service-account: "{{ .project.prefix }}-{{ .env }}-solr-autoscaling-operator@{{ .project.id }}.iam.gserviceaccount.com"
    {{- end }}
    {{- end }}
  {{- end }}