apiVersion: v1
kind: Service
metadata:
  name: {{ include "solr-autoscaling-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: solr-autoscaling-operator
