apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "fusion-basistech.serviceAccountName" . }}
  namespace: {{ include "fusion-basistech.namespace" . }}
  annotations:
    {{- include "fusion-basistech.roleHookAnnotations" . | nindent 4 }}