apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "fusion-basistech.temporaryPersistentVolumeClaim" . }}
  namespace: {{ include "fusion-basistech.namespace" . }}
  labels:
    type: local
  annotations:
    {{- include "fusion-basistech.preInstallAnnotations" . | nindent 4 }}
spec:
  {{- if .Values.storageClassName }}
  storageClassName: {{ .Values.storageClassName }}
  # {{- else }}
  # storageClassName: manual
  {{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage }}