apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "phantom-replica-service.fullname" . }}
  labels:
    {{- include "phantom-replica-service.labels" . | nindent 4 }}
spec:
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 300
  schedule: {{ .Values.cronjob.schedule | quote }}
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 60
      template:
        spec:
          serviceAccountName: phantom-replica-service-account
  {{-  if .Values.imagePullSecrets }}
          imagePullSecrets:
  {{ toYaml .Values.imagePullSecrets | indent 12 }}
  {{- end }}
          containers:
            - name: phantom-replica-service
              image: {{ .Values.cronjob.image.name }}:{{ .Values.cronjob.image.tag }}
              imagePullPolicy: {{ .Values.cronjob.image.pullPolicy }}
              env:
                - name: "PHANTOMREPLICASERVICE_CUSTOMERID"
                  value: {{ .Values.cronjob.customerId }}
                - name: "PHANTOMREPLICASERVICE_NAMESPACE"
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: "PHANTOMREPLICASERVICE_DELETE"
                  value: {{ .Values.cronjob.delete | quote }}
                - name: "PHANTOMREPLICASERVICE_OLDERTHANDAYS"
                  value: {{ .Values.cronjob.olderThanDays | quote }}
          restartPolicy: OnFailure
          nodeSelector:
            fusion_node_type: system
