kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: phantom-replica-service-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create", "get"]