apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "status-reader.clusterRoleName" . }}
  namespace: {{ include "status-reader.namespace" . }}
  labels:
    {{- include "status-reader.labels" . | nindent 4 }}
rules:
  - apiGroups:
    - ""
    resources:
    - nodes
    - persistentvolumes
    verbs:
    - get
    - list
    - watch
    - create
    - delete
