apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "status-reader.roleBindingName" . }}
  namespace: {{ include "status-reader.namespace" . }}
  labels:
    {{- include "status-reader.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "status-reader.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ include "status-reader.roleName" . }}
  apiGroup: rbac.authorization.k8s.io