apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "bouncer.fullname" . }}
  labels:
    {{- include "bouncer.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.cronjob.schedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: bouncer
  {{-  if .Values.imagePullSecrets }}
          imagePullSecrets:
  {{ toYaml .Values.imagePullSecrets | indent 12 }}
  {{- end }}
          containers:
            - name: bouncer
              image: {{ .Values.cronjob.image.name }}:{{ .Values.cronjob.image.tag }}
              imagePullPolicy: {{ .Values.cronjob.image.pullPolicy }}
              env:
                - name: "BOUNCER_CUSTOMERID"
                  value: {{ .Values.cronjob.customerId }}
                - name: "BOUNCER_NAMESPACE"
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: "BOUNCER_RETRIES_NUMBER"
                  value: {{ .Values.cronjob.retries.number | quote }}
                - name: "BOUNCER_RETRIES_WAITMINUTES"
                  value: {{ .Values.cronjob.retries.waitminutes | quote }}
                - name: "BOUNCER_BOUNCE_JOB_LAUNCHER"
                  value: {{ .Values.cronjob.bounce.job_launcher | quote }}
                - name: "BOUNCER_BOUNCE_CLASSIC_REST_SERVICE"
                  value: {{ .Values.cronjob.bounce.classic_rest_service | quote }}
                - name: "SERVICE_ACCOUNT_KEY"
                  valueFrom:
                    secretKeyRef:
                      key: sa
                      name: service-account-key
          restartPolicy: OnFailure
