apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bouncer
subjects:
  - kind: ServiceAccount
    name: bouncer
roleRef:
  kind: Role
  name: pod-bouncer
  apiGroup: rbac.authorization.k8s.io