apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "fluent-bit-aws.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "fluent-bit-aws.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "fluent-bit-aws.serviceAccountName" . }}
    namespace: {{ include "fluent-bit-aws.namespace" . }}
