apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "fluent-bit-aws.fullname" . }}
rules:
  - nonResourceURLs:
      - /metrics
    verbs:
      - get
  - apiGroups: [""]
    resources:
      - namespaces
      - pods
      - pods/logs
      - nodes
      - nodes/proxy
    verbs: ["get", "list", "watch"]
#  - apiGroups: ["policy"]
#    resources: ["podsecuritypolicies"]
#    verbs: ["use"]
#    resourceNames:
#      - {{ include "fluent-bit-aws.fullname" . }}
