apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "fluent-bit-aws.fullname" . }}
  namespace: {{ include "fluent-bit-aws.namespace" . }}
  labels:
    {{- include "fluent-bit-aws.labels" . | nindent 4 }}
spec:
  updateStrategy:
{{ toYaml .Values.updateStrategy | indent 4 }}
  selector:
    matchLabels:
      {{- include "fluent-bit-aws.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      {{- if .Values.annotations }}
        {{- toYaml .Values.annotations | nindent 8 }}
      {{- end }}
      labels:
        {{- include "fluent-bit-aws.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "fluent-bit-aws.serviceAccountName" . }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}
      {{- if .Values.hostNetwork }}
      hostNetwork: true
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
            - name: AWS_REGION
              value: {{ .Values.cloudwatch.region }}
            - name: CLUSTER_NAME
              value: {{ .Values.cloudwatch.clusterName }}
            - name: HTTP_SERVER
              value: {{ .Values.service.http.server }}
            - name: HTTP_PORT
              value: {{ .Values.service.http.port }}
            - name: READ_FROM_HEAD
              value: {{ .Values.cloudwatch.readFrom.head }}
            - name: READ_FROM_TAIL
              value: {{ .Values.cloudwatch.readFrom.tail }}
            - name: HOST_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: CI_VERSION
              value: "k8s/1.3.11"
          {{- if .Values.env }}
            {{- toYaml .Values.env | nindent 12 }}
          {{- end }}
          #   - name: fluentbit-config
          #     mountPath: /fluent-bit/etc/
            {{- if .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml .Values.volumeMounts | nindent 12 }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        # - name: fluentbit-config
        #   configMap:
        #     name: {{ include "fluent-bit-aws.fullname" . }}
        {{- if .Values.volumes }}
      volumes:
        {{- toYaml .Values.volumes | nindent 8 }}
        {{- end}}
      {{- if .Values.tolerations }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
