{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "fluent-bit-aws.serviceAccountName" . }}
  namespace: {{ include "fluent-bit-aws.namespace" . }}
  labels:
    {{- include "fluent-bit-aws.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
