kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fusion-metadata-agent-role
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "create", "update"]