apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding

metadata:
  name: {{ include "fusion-replication-check.clusterRoleBindingName" . }}
  namespace: {{ include "fusion-replication-check.namespace" . }}
roleRef:
  kind: ClusterRole
  name: {{ include "fusion-replication-check.clusterRoleName" . }}
  apiGroup: rbac.authorization.k8s.io

subjects:
  - kind: ServiceAccount
    name: {{ include "fusion-replication-check.serviceAccountName" . }}
    namespace: {{ include "fusion-replication-check.namespace" . }}