apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fusion-replication-check.fullname" . }}
  namespace: {{ include "fusion-replication-check.namespace" . }}
data:
  collections.txt: |
{{- .Values.collections | nindent 4 }}

{{ (.Files.Glob "scripts/*").AsConfig | indent 2 }}