apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "fusion-replication-check.fullname" . }}
  namespace: {{ template "fusion-replication-check.namespace" . }}
spec:
  storageClassName: {{ .Values.storage.className | default "standard" }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size }}