cronjob:
  schedule: "0 0 * * *"
  customerId: "test"
  retries:
    number: "12"
    waitminutes: "5"
  bounce:
    job_launcher: "true"
    classic_rest_service: "true"
  image:
    name: us-west1-docker.pkg.dev/managed-fusion/cloud-support/images/bouncer
    pullPolicy: Always
    tag: 1.3.0

imagePullSecrets:
  - name: gcr-managed-fusion
nameOverride: ""
fullnameOverride: ""